services:
  - type: web
    name: shukla-law-firm
    env: node
    plan: free
    region: oregon
    buildCommand: npm run build
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
